Repository Foxx-org/exorium, pull requests merged in 2021-05, with the labels that each got.

#110 Push rewrite to main
  bot.py
  cogs/DLP.py
  cogs/admin.py
  cogs/error.py
  cogs/events/error.py
  cogs/events/logs.py
  cogs/events/statcord.py
  cogs/help.py
  cogs/social.py
  cogs/social_slash.py
  config.example.py
  utils/checks.py
  utils/default.py
  utils/help.py
Labels: enhancement, fix, high priority

#124 adding post stats for DEL
  cogs/DLP.py
  requirements.txt
Labels: fix

#127 Ban command -> Ban people not in the guild
  cogs/mod.py
Labels: enhancement

#123 Update help.py
  cogs/admin.py
  cogs/help.py
  cogs/mod.py
Labels: enhancement
